# referência
# https://github.com/bbatsov/rubocop/blob/master/config/default.yml

AllCops:
  TargetRubyVersion: '2.5'
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'lib/tasks/*.rake'
    - 'lib/tasks/rake_helper.rb'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'

Rails:
  Enabled: true

Documentation:
  Enabled: false

AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Metrics/LineLength:
  Max: 120
  Exclude:
    - config/initializers/secret_token.rb

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
    - "spec/factories/**"
