version: '2'
services:
  db:
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: '123@Oliveira4'
    image: 'microsoft/mssql-server-linux'
    ports:
      - 1433:1433
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data:
